### ISSUE TITLE
用的哪里的词库，感觉这个词库有问题

### ISSUE THREAD

**Issue by JeffreyBool** [go-creed/sat#1]
`炤` 转换简体为 `照` 了结果， 在其他词库这个字就是 `炤`

**Comment by go-creed** [comment]
这是地址 http://xh.5156edu.com/html3/10954.html
![image](https://user-images.githubusercontent.com/28722936/94637599-950ac780-030a-11eb-8840-792d185f50a1.png)

你可以对有疑问的词自己配置个地址
